apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: apimatic-codegen-openshift-pipelines-demo
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: apimatic-codegen-openshift-pipelines-demo
  template:
    ref: apimatic-codegen-openshift-pipelines-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "1234567"
