apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-portal-zip
spec:
  workspaces:
  - name: portalzip
  params:
    - name: apimatic-codegen-service
      description: The OpenShift codegen service URL running on cluster
      type: string
  steps:
    - name: curl
      image: quay.io/apimatic/http-server-base:stable
      workingDir: /workspace/portalzip
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Obtaining portal.zip file from APIMatic Codegen app running in cluster
          curl -X POST --url $(inputs.params.apimatic-codegen-service):8080/api/build -F "file=@apimatic.zip" >> portal.zip
