apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: zip-build-folder
spec:
  workspaces:
  - name: buildfolder
  params:
    - name: portal_dir
      description: The directory in source that contains APIMatic portal build file and associated assets
      type: string
      default: Portal
  steps:
    - name: zip
      image: quay.io/apimatic/http-server-base:stable
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Zipping the $(inputs.params.portal_dir) directory
          cd $(workspaces.buildfolder.path)/$(inputs.params.portal_dir)
          zip -r $(workspaces.buildfolder.path)/apimatic.zip .
