apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-api-pipelinerun
spec:
  serviceAccountName: openshift-pipelines-operator
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: apimatic-dx-portal-demo
  - name: git-url
    value: https://github.com/Obaid-Rehman/apimatic-codegen-openshift-pipelines-demo.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/apimatic-dx-portal
  - name: apimatic-codegen-service
    value: codegen-sample.openshift-operators.svc.cluster.local
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
